create table users (
    id bigserial primary key,
    username text not null unique,
    email text null unique,
    email_verification_sent timestamptz null default null,
    email_verified timestamptz null default null,
    hard_banned bool not null default false,

    password text null default null,
    tfa_mode int null default null,
    tfa_data text null default null,

    created_at timestamptz not null default now()
);

create table auth_sources (
    id bigint not null generated by default as identity primary key,
    user_id bigint not null references users on delete cascade,
    provider int not null,
    provider_account_id text,
    refresh_token text,
    access_token text,
    expires_at timestamptz,
    scope text,
    id_token text,

    created_at timestamptz not null default now()
);
